//! Generator: turns a [`DatabaseSchema`] into a single-file Rust crate.

use anyhow::Result;
use hr_dataverse::{ColumnDefinition, DatabaseSchema, FieldType, IdStrategy, TableDefinition};

/// Produce the contents of `Cargo.toml` for a generated `dv-{slug}` crate.
/// Stable across regenerations (so it can be committed without churn).
pub fn generate_cargo_toml(slug: &str) -> String {
    let crate_name = format!("dv-{}", slug.replace('_', "-"));
    format!(
        "# Generated by hr-dv-codegen — Cargo.toml is committed, src/ is regenerated.\n\
         [package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2024\"\n\n\
         [dependencies]\n\
         serde = {{ version = \"1\", features = [\"derive\"] }}\n\
         serde_json = \"1\"\n\
         chrono = {{ version = \"0.4\", features = [\"serde\"] }}\n\
         reqwest = {{ version = \"0.13\", default-features = false, features = [\"rustls\", \"json\"] }}\n\
         thiserror = \"2\"\n",
        name = crate_name
    )
}

/// Produce `src/lib.rs` content.
pub fn generate_lib(slug: &str, schema: &DatabaseSchema) -> Result<String> {
    let mut s = String::new();
    s.push_str(&header(slug, schema));
    s.push_str(PREAMBLE);
    s.push_str(ERROR_TYPES);
    s.push_str(CLIENT_BASE);

    // Shared helpers (ListParams + URL encoder) — emitted once per crate.
    s.push_str(list_params_helper());

    // Top-level `DvClient::table_name()` accessors.
    s.push_str("impl DvClient {\n");
    for table in &schema.tables {
        let snake = table.name.as_str();
        let builder = builder_name(snake);
        s.push_str(&format!(
            "    pub fn {snake}(&self) -> {builder}<'_> {{ {builder} {{ client: self }} }}\n",
        ));
    }
    s.push_str("}\n\n");

    for table in &schema.tables {
        s.push_str(&generate_table_module(table));
    }

    Ok(s)
}

fn header(slug: &str, schema: &DatabaseSchema) -> String {
    format!(
        "//! Generated by hr-dv-codegen — DO NOT EDIT.\n\
         //!\n\
         //! Slug: {slug}\n\
         //! Schema version: {ver}\n\
         //! Tables: {n}\n\n",
        slug = slug,
        ver = schema.version,
        n = schema.tables.len()
    )
}

const PREAMBLE: &str = r#"#![allow(dead_code, unused_imports)]

use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::collections::BTreeMap;

"#;

const ERROR_TYPES: &str = r#"#[derive(Debug, thiserror::Error)]
pub enum DvError {
    #[error("http: {0}")]
    Http(#[from] reqwest::Error),
    #[error("env var {0} not set — apps need HR_DV_BASE_URL and HR_DV_TOKEN injected by the orchestrator")]
    MissingEnv(&'static str),
    #[error("not found")]
    NotFound,
    #[error("precondition failed (version mismatch on If-Match)")]
    PreconditionFailed,
    #[error("unauthorized")]
    Unauthorized,
    #[error("unprocessable: {0}")]
    Unprocessable(String),
    #[error("gateway error {status}: {message}")]
    Gateway { status: u16, message: String },
    #[error("decode: {0}")]
    Decode(String),
}

pub type DvResult<T> = std::result::Result<T, DvError>;

#[derive(Debug, Deserialize)]
struct ErrorEnvelope {
    error: ErrorBody,
}

#[derive(Debug, Deserialize)]
struct ErrorBody {
    #[serde(default)]
    code: String,
    #[serde(default)]
    message: String,
}

#[derive(Debug, Deserialize)]
struct ListEnvelope<T> {
    // No `#[serde(default)]` here: that would require `T: Default` on every
    // generated row struct (which we deliberately don't derive — some
    // future field types may not be `Default`-friendly). The gateway
    // always returns a `value` array so default is never needed.
    value: Vec<T>,
    #[serde(rename = "@count", default)]
    count: Option<i64>,
}

"#;

const CLIENT_BASE: &str = r#"/// Typed client for the dataverse REST gateway. Reads its base URL and
/// bearer token from `HR_DV_BASE_URL` and `HR_DV_TOKEN` (injected by the
/// orchestrator at app start).
#[derive(Clone)]
pub struct DvClient {
    base_url: String,
    token: String,
    http: reqwest::Client,
}

impl DvClient {
    /// Construct from the env vars injected by hr-orchestrator.
    pub fn from_env() -> DvResult<Self> {
        let base_url = std::env::var("HR_DV_BASE_URL").map_err(|_| DvError::MissingEnv("HR_DV_BASE_URL"))?;
        let token = std::env::var("HR_DV_TOKEN").map_err(|_| DvError::MissingEnv("HR_DV_TOKEN"))?;
        Ok(Self::new(base_url, token))
    }

    pub fn new(base_url: impl Into<String>, token: impl Into<String>) -> Self {
        Self {
            base_url: base_url.into().trim_end_matches('/').to_string(),
            token: token.into(),
            http: reqwest::Client::builder()
                .build()
                .expect("reqwest::Client::build"),
        }
    }

    pub fn base_url(&self) -> &str { &self.base_url }

    fn endpoint(&self, path: &str) -> String {
        format!("{}{}", self.base_url, path)
    }

    fn auth(&self, b: reqwest::RequestBuilder) -> reqwest::RequestBuilder {
        b.bearer_auth(&self.token)
    }

    async fn handle<T: serde::de::DeserializeOwned>(resp: reqwest::Response) -> DvResult<T> {
        let status = resp.status();
        if status.is_success() {
            return resp.json::<T>().await.map_err(|e| DvError::Decode(e.to_string()));
        }
        let raw = resp.text().await.unwrap_or_default();
        let parsed: Result<ErrorEnvelope, _> = serde_json::from_str(&raw);
        let message = parsed
            .as_ref()
            .map(|e| e.error.message.clone())
            .unwrap_or_else(|_| raw.clone());
        match status.as_u16() {
            401 => Err(DvError::Unauthorized),
            404 => Err(DvError::NotFound),
            412 => Err(DvError::PreconditionFailed),
            422 => Err(DvError::Unprocessable(message)),
            _ => Err(DvError::Gateway { status: status.as_u16(), message }),
        }
    }

    /// Escape hatch for partial updates that need to send `null` explicitly
    /// (e.g. clearing a nullable foreign key). The typed `*Update` structs
    /// emitted by the codegen carry `#[serde(skip_serializing_if = "Option::is_none")]`
    /// to preserve partial-update semantics, which makes it impossible to
    /// distinguish "leave alone" from "set to null". Use this method when
    /// you need the latter; pass a `serde_json::Value` whose keys are the
    /// columns you want to set, with `Value::Null` to clear.
    ///
    /// Example: clearing a folder's parent (move-to-root):
    /// ```ignore
    /// dv.patch_row_raw("folders", &serde_json::json!(folder_id), version,
    ///                  &serde_json::json!({"parent_id": null})).await?;
    /// ```
    pub async fn patch_row_raw(
        &self,
        table: &str,
        id: &Value,
        version: i32,
        body: &Value,
    ) -> DvResult<Value> {
        let id_str = match id {
            Value::String(s) => s.clone(),
            Value::Number(n) => n.to_string(),
            other => return Err(DvError::Unprocessable(
                format!("patch_row_raw: id must be string or number, got {:?}", other)
            )),
        };
        let url = format!("{}/{}/{}", self.base_url, table, id_str);
        let resp = self.auth(self.http.patch(&url))
            .header("If-Match", version.to_string())
            .json(body)
            .send().await?;
        Self::handle(resp).await
    }
}

"#;

fn generate_table_module(table: &TableDefinition) -> String {
    let mut s = String::new();
    let row_struct = pascal(&table.name);
    let insert_struct = format!("{}Insert", row_struct);
    let update_struct = format!("{}Update", row_struct);
    let builder_struct = builder_name(&table.name);
    let id_ty = match table.id_strategy {
        IdStrategy::Bigserial => "i64",
        IdStrategy::Uuid => "String",
    };
    let id_path_fmt = match table.id_strategy {
        IdStrategy::Bigserial => "{id}",
        IdStrategy::Uuid => "{id}",
    };
    let _ = id_path_fmt;

    // ── Row struct ──────────────────────────────────────────────
    s.push_str(&format!(
        "// ── table: {} ────────────────────────────────────────\n\n",
        table.name
    ));
    s.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    s.push_str(&format!("pub struct {} {{\n", row_struct));
    s.push_str(&format!("    pub id: {},\n", id_ty));
    s.push_str("    #[serde(default)]\n");
    s.push_str("    pub created_at: Option<DateTime<Utc>>,\n");
    s.push_str("    #[serde(default)]\n");
    s.push_str("    pub updated_at: Option<DateTime<Utc>>,\n");
    s.push_str("    #[serde(default)]\n");
    s.push_str("    pub version: i32,\n");
    s.push_str("    #[serde(default)]\n");
    s.push_str("    pub is_deleted: bool,\n");
    for col in &table.columns {
        s.push_str("    #[serde(default)]\n");
        s.push_str(&format!(
            "    pub {field}: Option<{ty}>,\n",
            field = sanitize_field(&col.name),
            ty = field_to_rust_type(col)
        ));
    }
    s.push_str("}\n\n");

    // ── Insert / Update structs ─────────────────────────────────
    s.push_str("#[derive(Debug, Default, Clone, Serialize)]\n");
    s.push_str(&format!("pub struct {} {{\n", insert_struct));
    for col in &table.columns {
        s.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
        s.push_str(&format!(
            "    pub {field}: Option<{ty}>,\n",
            field = sanitize_field(&col.name),
            ty = field_to_rust_type(col)
        ));
    }
    s.push_str("}\n\n");

    s.push_str("#[derive(Debug, Default, Clone, Serialize)]\n");
    s.push_str(&format!("pub struct {} {{\n", update_struct));
    for col in &table.columns {
        s.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
        s.push_str(&format!(
            "    pub {field}: Option<{ty}>,\n",
            field = sanitize_field(&col.name),
            ty = field_to_rust_type(col)
        ));
    }
    s.push_str("}\n\n");

    // ── Builder ─────────────────────────────────────────────────
    s.push_str(&format!(
        "pub struct {bld}<'a> {{ pub(crate) client: &'a DvClient }}\n\n",
        bld = builder_struct
    ));

    // Builder impl — string-concat; we use `replace` for the few
    // table-specific tokens to dodge format!'s `{...}` headache.
    let methods = METHODS_TEMPLATE
        .replace("__BUILDER__", &builder_struct)
        .replace("__ROW__", &row_struct)
        .replace("__INSERT__", &insert_struct)
        .replace("__UPDATE__", &update_struct)
        .replace("__ID_TY__", id_ty)
        .replace("__TBL_PATH__", &format!("/{}", table.name));
    s.push_str(&methods);
    s.push_str("\n");

    s
}

/// Template for the `impl <Builder>` block. Placeholders are
/// double-underscore-wrapped tokens so they don't collide with Rust's
/// `format!` syntax (`{}`).
const METHODS_TEMPLATE: &str = r#"impl<'a> __BUILDER__<'a> {
    const PATH: &'static str = "__TBL_PATH__";

    /// `GET /{table}` — convenience for `list_with(ListParams::default())`.
    pub async fn list(&self) -> DvResult<Vec<__ROW__>> {
        self.list_with(ListParams::default()).await
    }

    /// `GET /{table}` with OData query params (`$filter`, `$select`, …).
    pub async fn list_with(&self, params: ListParams) -> DvResult<Vec<__ROW__>> {
        let mut url = self.client.endpoint(Self::PATH);
        let mut q: Vec<(String, String)> = Vec::new();
        if let Some(f) = params.filter { q.push(("$filter".into(), f)); }
        if !params.select.is_empty() { q.push(("$select".into(), params.select.join(","))); }
        if !params.orderby.is_empty() { q.push(("$orderby".into(), params.orderby.join(","))); }
        if let Some(t) = params.top { q.push(("$top".into(), t.to_string())); }
        if let Some(s) = params.skip { q.push(("$skip".into(), s.to_string())); }
        if params.include_deleted { q.push(("$includeDeleted".into(), "true".into())); }
        if !q.is_empty() { url.push('?'); url.push_str(&serde_urlencoded_lite(&q)); }
        let resp = self.client.auth(self.client.http.get(&url)).send().await?;
        let env: ListEnvelope<__ROW__> = DvClient::handle(resp).await?;
        Ok(env.value)
    }

    /// `GET /{table}/{id}`. Returns `Ok(None)` on 404.
    pub async fn get(&self, id: __ID_TY__) -> DvResult<Option<__ROW__>> {
        let mut url = self.client.endpoint(Self::PATH);
        url.push('/');
        url.push_str(&id.to_string());
        match DvClient::handle::<__ROW__>(self.client.auth(self.client.http.get(&url)).send().await?).await {
            Ok(r) => Ok(Some(r)),
            Err(DvError::NotFound) => Ok(None),
            Err(e) => Err(e),
        }
    }

    /// `POST /{table}` — insert a new row.
    pub async fn insert(&self, payload: __INSERT__) -> DvResult<__ROW__> {
        let url = self.client.endpoint(Self::PATH);
        let resp = self.client.auth(self.client.http.post(&url)).json(&payload).send().await?;
        DvClient::handle(resp).await
    }

    /// `PATCH /{table}/{id}` with `If-Match: <version>`. Returns
    /// `Err(DvError::PreconditionFailed)` on version mismatch.
    pub async fn update(&self, id: __ID_TY__, version: i32, payload: __UPDATE__) -> DvResult<__ROW__> {
        let mut url = self.client.endpoint(Self::PATH);
        url.push('/');
        url.push_str(&id.to_string());
        let resp = self.client.auth(self.client.http.patch(&url))
            .header("If-Match", version.to_string())
            .json(&payload)
            .send().await?;
        DvClient::handle(resp).await
    }

    /// `DELETE /{table}/{id}` with `If-Match: <version>` — soft-delete.
    pub async fn delete(&self, id: __ID_TY__, version: i32) -> DvResult<__ROW__> {
        let mut url = self.client.endpoint(Self::PATH);
        url.push('/');
        url.push_str(&id.to_string());
        let resp = self.client.auth(self.client.http.delete(&url))
            .header("If-Match", version.to_string())
            .send().await?;
        DvClient::handle(resp).await
    }

    /// `POST /{table}/$restore/{id}` with `If-Match: <version>`.
    pub async fn restore(&self, id: __ID_TY__, version: i32) -> DvResult<__ROW__> {
        let mut url = self.client.endpoint(Self::PATH);
        url.push_str("/$restore/");
        url.push_str(&id.to_string());
        let resp = self.client.auth(self.client.http.post(&url))
            .header("If-Match", version.to_string())
            .send().await?;
        DvClient::handle(resp).await
    }
}
"#;

const _LIST_PARAMS_AND_HELPER: &str = ""; // placeholder

fn field_to_rust_type(col: &ColumnDefinition) -> &'static str {
    match col.field_type {
        FieldType::Text
        | FieldType::Email
        | FieldType::Url
        | FieldType::Phone
        | FieldType::Choice
        | FieldType::Time
        | FieldType::Duration
        | FieldType::Formula => "String",
        FieldType::Number | FieldType::AutoIncrement | FieldType::Lookup => "i64",
        FieldType::Decimal | FieldType::Currency | FieldType::Percent => "f64",
        FieldType::Boolean => "bool",
        FieldType::DateTime => "chrono::DateTime<chrono::Utc>",
        FieldType::Date => "chrono::NaiveDate",
        FieldType::Json => "serde_json::Value",
        FieldType::Uuid => "String",
        FieldType::MultiChoice => "Vec<String>",
    }
}

/// Convert a snake_case name to PascalCase, applying naïve singularisation
/// (drop trailing `s`, `ies`→`y`). Used for **row** struct names — the
/// builder uses the as-is plural form via [`pascal_plural`].
fn pascal(name: &str) -> String {
    snake_to_pascal(&singular(name))
}

/// Same as [`pascal`] but keeps the original (plural) form. Used for the
/// builder struct so `dv.transactions()` reads naturally as a collection.
fn pascal_plural(name: &str) -> String {
    snake_to_pascal(name)
}

/// Pick a builder struct name that doesn't collide with the row struct.
///
/// For pluralisable tables (`transactions` → row=`Transaction`,
/// builder=`Transactions`) the two names differ naturally and we use the
/// plural form. For tables where the name has no plural marker
/// (`command_history`, `file_metadata`, `address`) the row and the as-is
/// pascal name collide, producing duplicate `pub struct` definitions
/// → uncompilable code. In that case we append a `Table` suffix to the
/// builder so it stays unique while keeping the row struct unchanged.
fn builder_name(name: &str) -> String {
    let row = pascal(name);
    let plural = pascal_plural(name);
    if row == plural {
        format!("{}Table", row)
    } else {
        plural
    }
}

fn snake_to_pascal(name: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in name.chars() {
        if c == '_' {
            up = true;
            continue;
        }
        if up {
            out.extend(c.to_uppercase());
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn singular(name: &str) -> String {
    // Words whose plural ends in `ies` but whose singular ends in `ie`
    // (not `y`). The default `ies → y` rule mangles `movies → movy`,
    // `pies → py`, etc. We strip just the trailing `s` for these.
    // Detection is done on the last underscore-separated segment so
    // `recipe_movies` follows the same path as `movies`.
    const IES_KEEP_IE: &[&str] = &[
        "movies", "pies", "lies", "ties", "cookies", "brownies", "selfies", "zombies",
    ];
    let last_segment = name.rsplit('_').next().unwrap_or(name);
    if IES_KEEP_IE.contains(&last_segment) {
        return name.strip_suffix('s').unwrap_or(name).to_string();
    }
    if let Some(stem) = name.strip_suffix("ies") {
        format!("{}y", stem)
    } else if name.ends_with("ss") {
        // "address" → keep
        name.to_string()
    } else if let Some(stem) = name.strip_suffix('s') {
        stem.to_string()
    } else {
        name.to_string()
    }
}

/// Sanitise a column name to be a valid Rust identifier. Leaves
/// snake_case names untouched; replaces invalid chars with `_`.
fn sanitize_field(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut chars = name.chars();
    if let Some(c) = chars.next() {
        if c.is_ascii_alphabetic() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    for c in chars {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    // Avoid Rust keywords (extend list as needed).
    if matches!(
        out.as_str(),
        "type" | "self" | "super" | "crate" | "mod" | "as" | "where" | "ref" | "use" | "fn" | "let"
    ) {
        out.push('_');
    }
    out
}

/// Generated the helper `ListParams` struct + URL-encoder. Emitted once
/// per crate (shared by every table's `list_with`).
pub fn list_params_helper() -> &'static str {
    r#"
/// Optional query parameters for `list_with`.
#[derive(Debug, Default, Clone)]
pub struct ListParams {
    pub filter: Option<String>,
    pub select: Vec<String>,
    pub orderby: Vec<String>,
    pub top: Option<u32>,
    pub skip: Option<u32>,
    pub include_deleted: bool,
}

impl ListParams {
    pub fn filter(mut self, f: impl Into<String>) -> Self { self.filter = Some(f.into()); self }
    pub fn select(mut self, cols: &[&str]) -> Self {
        self.select = cols.iter().map(|s| s.to_string()).collect(); self
    }
    pub fn orderby(mut self, items: &[&str]) -> Self {
        self.orderby = items.iter().map(|s| s.to_string()).collect(); self
    }
    pub fn top(mut self, n: u32) -> Self { self.top = Some(n); self }
    pub fn skip(mut self, n: u32) -> Self { self.skip = Some(n); self }
    pub fn include_deleted(mut self, v: bool) -> Self { self.include_deleted = v; self }
}

/// Tiny URL-encoder so the generated crate doesn't need a `serde_urlencoded`
/// dependency. Escapes everything outside the unreserved set per RFC3986.
fn serde_urlencoded_lite(pairs: &[(String, String)]) -> String {
    fn enc(s: &str) -> String {
        let mut out = String::with_capacity(s.len());
        for c in s.chars() {
            match c {
                'A'..='Z' | 'a'..='z' | '0'..='9' | '-' | '_' | '.' | '~' => out.push(c),
                _ => {
                    for b in c.to_string().as_bytes() {
                        out.push_str(&format!("%{:02X}", b));
                    }
                }
            }
        }
        out
    }
    pairs
        .iter()
        .map(|(k, v)| format!("{}={}", enc(k), enc(v)))
        .collect::<Vec<_>>()
        .join("&")
}
"#
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use hr_dataverse::{ColumnDefinition, DatabaseSchema, FieldType, IdStrategy, TableDefinition};

    fn col(name: &str, t: FieldType) -> ColumnDefinition {
        ColumnDefinition {
            name: name.into(),
            field_type: t,
            required: false,
            unique: false,
            default_value: None,
            description: None,
            choices: vec![],
            formula_expression: None,
            lookup_target: None,
        }
    }

    fn schema_with_one_table() -> DatabaseSchema {
        DatabaseSchema {
            tables: vec![TableDefinition {
                name: "transactions".into(),
                slug: "transactions".into(),
                columns: vec![
                    col("date", FieldType::Date),
                    col("label", FieldType::Text),
                    col("amount", FieldType::Decimal),
                    col("settled", FieldType::Boolean),
                ],
                description: None,
                id_strategy: IdStrategy::Bigserial,
                created_at: Utc::now(),
                updated_at: Utc::now(),
            }],
            relations: vec![],
            version: 1,
            updated_at: None,
        }
    }

    #[test]
    fn pascal_singularises_simple_plurals() {
        assert_eq!(pascal("transactions"), "Transaction");
        assert_eq!(pascal("settings"), "Setting");
        assert_eq!(pascal("import_logs"), "ImportLog");
        assert_eq!(pascal("address"), "Address");
        assert_eq!(pascal("companies"), "Company");
    }

    #[test]
    fn pascal_handles_irregular_ies_keep_ie() {
        // `movies` is the plural of `movie`, not `movy`. The naïve
        // `ies → y` rule is wrong here and was producing uncompilable
        // output downstream. Same family: pies, ties, cookies …
        assert_eq!(pascal("movies"), "Movie");
        assert_eq!(pascal("pies"), "Pie");
        assert_eq!(pascal("recipe_cookies"), "RecipeCookie");
        // The `ies → y` rule still applies for the regular case.
        assert_eq!(pascal("histories"), "History");
        assert_eq!(pascal("categories"), "Category");
    }

    #[test]
    fn builder_name_appends_table_when_collision() {
        // Pluralisable names have row != builder, so no suffix needed.
        assert_eq!(builder_name("transactions"), "Transactions");
        assert_eq!(builder_name("movies"), "Movies");

        // Non-pluralisable names (no trailing `s`, or `ss`) collide:
        // `pascal(file_metadata) == pascal_plural(file_metadata) ==
        // FileMetadata`. Without the suffix the generated Rust file
        // contains two `pub struct FileMetadata` declarations and won't
        // compile. With the suffix we get `FileMetadata` (row) and
        // `FileMetadataTable` (builder).
        assert_eq!(builder_name("file_metadata"), "FileMetadataTable");
        assert_eq!(builder_name("command_history"), "CommandHistoryTable");
        assert_eq!(builder_name("address"), "AddressTable");
        assert_eq!(builder_name("recipe_suggestions_history"), "RecipeSuggestionsHistoryTable");
        assert_eq!(builder_name("files_fts_config"), "FilesFtsConfigTable");
    }

    #[test]
    fn sanitize_field_handles_keywords() {
        assert_eq!(sanitize_field("type"), "type_");
        assert_eq!(sanitize_field("amount"), "amount");
        assert_eq!(sanitize_field("user-id"), "user_id");
    }

    #[test]
    fn generate_lib_compiles_to_string() {
        let schema = schema_with_one_table();
        let out = generate_lib("wallet", &schema).unwrap();
        assert!(out.contains("pub struct Transaction "));
        assert!(out.contains("pub struct TransactionInsert"));
        assert!(out.contains("pub struct TransactionUpdate"));
        // Builder struct keeps the plural; method name matches the table name.
        assert!(out.contains("pub struct Transactions<'a>"));
        assert!(out.contains("pub fn transactions(&self) -> Transactions<'_>"));
        assert!(out.contains("pub async fn insert(&self, payload: TransactionInsert)"));
        assert!(out.contains("If-Match"));
    }

    #[test]
    fn cargo_toml_shape() {
        let toml = generate_cargo_toml("wallet");
        assert!(toml.contains("name = \"dv-wallet\""));
        assert!(toml.contains("reqwest"));
    }
}
