[repository]
repository = "sftp:romain@10.0.0.20:/backup/homeroute/rustic"

[repository.options]
sftp.command = "ssh romain@10.0.0.20 -i /root/.ssh/id_ed25519_backup -o StrictHostKeyChecking=no -o BatchMode=yes -s sftp"
